import React from "react";
import { useIntl } from "react-intl";
import { translations } from "@/util";

export type TranslationKey = keyof ReturnType<typeof translations>;
export type TranslationFunction = ReturnType<
	typeof translations
>[TranslationKey];

/**
 * A hook that returns the translation for a given ID
 * Check the `translations` object above for the list of IDs and how to add more translations
 * @param id The ID of the translation generated by React Intl
 */
export const useTranslations = () => {
	const intl = useIntl();
	// the translations is quite expensive to generate, so we memoize it
	const translationObject = React.useMemo(() => translations(intl), [intl]);
	return translationObject;
};
