name: Test gh context

on: [push, pull_request]

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"

      # ... rest of your steps ...
